let _jsPDF = null;
async function loadJsPDF() {
  if (!_jsPDF) {
    const mod = await import('jspdf');
    await import('jspdf-autotable');
    _jsPDF = mod.jsPDF;
  }
  return _jsPDF;
}

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const MONTHS_SHORT = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

function createDoc(JsPDF, title, farmName) {
  const doc = new JsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  // Header bar
  doc.setFillColor(74, 124, 46); // #4a7c2e
  doc.rect(0, 0, 210, 18, 'F');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(`🌱 ${farmName || 'BioGrow'}`, 10, 12);
  doc.setFontSize(9);
  doc.text(title, 210 - 10, 12, { align: 'right' });
  // Date
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), 210 - 10, 7, { align: 'right' });
  doc.setTextColor(0, 0, 0);
  return doc;
}

function addFooter(doc) {
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by BioGrow — biogrow.app', 10, 290);
    doc.text(`Page ${i} of ${pages}`, 200, 290, { align: 'right' });
  }
}

function weekToMonth(week) {
  if (week < 1) return 0;
  if (week > 52) return 11;
  const d = new Date(new Date().getFullYear(), 0, 1);
  d.setDate(d.getDate() + (week - 1) * 7);
  return d.getMonth();
}

// --- Export 1: Farm Plan ---
export async function exportFarmPlanPdf({ zones, crops, settings, user }) {
  const JsPDF = await loadJsPDF();
  const farmName = user?.profile?.farmName || 'My Farm';
  const year = settings?.currentYear || new Date().getFullYear();
  const doc = createDoc(JsPDF, `Farm Plan ${year}`, farmName);

  let y = 26;
  doc.setFontSize(16);
  doc.setTextColor(44, 24, 16);
  doc.text(`Farm Plan — Season ${year}`, 10, y);
  y += 10;

  // Stats summary
  const totalBeds = zones.reduce((s, z) => s + (z.beds?.length || 0), 0);
  const totalArea = zones.reduce((s, z) => s + z.beds.reduce((a, b) => a + (b.width || 0.75) * (b.length || 10), 0), 0);
  const plantings = [];
  zones.forEach(z => z.beds.forEach(b => (b.plantings || []).forEach(p => {
    if (p.year === year) plantings.push({ ...p, bedName: b.name, zoneName: z.name });
  })));
  const cropSet = new Set(plantings.map(p => p.cropId));

  doc.autoTable({
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Zones', zones.length],
      ['Total Beds', totalBeds],
      ['Growing Area', `${totalArea.toFixed(1)} m²`],
      ['Active Plantings', plantings.length],
      ['Crop Varieties', cropSet.size],
      ['Last Frost Week', settings?.lastFrostWeek || 12],
      ['First Frost Week', settings?.firstFrostWeek || 44],
    ],
    theme: 'grid',
    headStyles: { fillColor: [74, 124, 46], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 10, right: 10 },
  });

  y = doc.lastAutoTable.finalY + 10;

  // Planting table
  if (plantings.length > 0) {
    doc.setFontSize(12);
    doc.text('Planting Schedule', 10, y);
    y += 4;

    const rows = plantings.map(p => {
      const crop = crops.find(c => c.id === p.cropId);
      return [
        p.zoneName,
        p.bedName,
        crop?.name || 'Unknown',
        `Week ${p.startWeek}`,
        crop?.daysToMaturity ? `${crop.daysToMaturity}d` : '—',
        p.bedFraction === 1 ? 'Full' : p.bedFraction === 0.5 ? '½' : '¼',
      ];
    });

    doc.autoTable({
      startY: y,
      head: [['Zone', 'Bed', 'Crop', 'Start', 'Maturity', 'Fraction']],
      body: rows,
      theme: 'striped',
      headStyles: { fillColor: [74, 124, 46], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 10, right: 10 },
    });
  }

  addFooter(doc);
  doc.save(`${farmName.replace(/\s+/g, '-')}-farm-plan-${year}.pdf`);
}

// --- Export 2: Season Calendar ---
export async function exportSeasonCalendarPdf({ zones, crops, settings, user }) {
  const JsPDF = await loadJsPDF();
  const farmName = user?.profile?.farmName || 'My Farm';
  const year = settings?.currentYear || new Date().getFullYear();
  const doc = createDoc(JsPDF, `Season Calendar ${year}`, farmName);

  // Gather monthly data (same logic as printCalendar.js)
  const monthData = MONTHS.map(() => ({ sow: [], transplant: [], harvest: [] }));
  (zones || []).forEach(z => (z.beds || []).forEach(b => {
    (b.plantings || []).forEach(p => {
      if (p.year !== year) return;
      const crop = crops.find(c => c.id === p.cropId);
      if (!crop) return;
      const sw = parseInt(p.startWeek);
      if (isNaN(sw)) return;
      const sowM = weekToMonth(sw);
      if (sowM >= 0 && sowM < 12 && !monthData[sowM].sow.find(x => x.id === crop.id))
        monthData[sowM].sow.push({ id: crop.id, name: crop.name });
      const dic = crop.daysInCell || 0;
      if (dic > 0) {
        const tM = weekToMonth(sw + Math.ceil(dic / 7));
        if (tM >= 0 && tM < 12 && !monthData[tM].transplant.find(x => x.id === crop.id))
          monthData[tM].transplant.push({ id: crop.id, name: crop.name });
      }
      const hM = weekToMonth(sw + Math.ceil((crop.daysToMaturity || 60) / 7));
      if (hM >= 0 && hM < 12 && !monthData[hM].harvest.find(x => x.id === crop.id))
        monthData[hM].harvest.push({ id: crop.id, name: crop.name });
    });
  }));

  let y = 26;
  doc.setFontSize(14);
  doc.text(`Season Calendar ${year}`, 10, y);
  y += 8;

  const rows = MONTHS.map((m, i) => [
    m,
    monthData[i].sow.map(c => c.name).join(', ') || '—',
    monthData[i].transplant.map(c => c.name).join(', ') || '—',
    monthData[i].harvest.map(c => c.name).join(', ') || '—',
  ]);

  doc.autoTable({
    startY: y,
    head: [['Month', 'Sow', 'Transplant', 'Harvest']],
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: [74, 124, 46], fontSize: 9 },
    bodyStyles: { fontSize: 8, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 25 }, 1: { cellWidth: 55 }, 2: { cellWidth: 55 }, 3: { cellWidth: 55 } },
    margin: { left: 10, right: 10 },
  });

  addFooter(doc);
  doc.save(`${farmName.replace(/\s+/g, '-')}-calendar-${year}.pdf`);
}

// --- Export 3: Harvest Report ---
export async function exportHarvestReportPdf({ harvests, crops, zones, settings, user }) {
  const JsPDF = await loadJsPDF();
  const farmName = user?.profile?.farmName || 'My Farm';
  const year = settings?.currentYear || new Date().getFullYear();
  const doc = createDoc(JsPDF, `Harvest Report ${year}`, farmName);

  const yearH = (harvests || []).filter(h => new Date(h.date).getFullYear() === year);
  const totalYield = yearH.reduce((s, h) => s + (parseFloat(h.weight) || 0), 0);
  const totalRevenue = yearH.reduce((s, h) => s + (parseFloat(h.weight) || 0) * (parseFloat(h.pricePerKg) || 0), 0);

  let y = 26;
  doc.setFontSize(14);
  doc.text(`Harvest Report — ${year}`, 10, y);
  y += 10;

  doc.autoTable({
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Total Harvests', yearH.length],
      ['Total Yield', `${totalYield.toFixed(1)} kg`],
      ['Total Revenue', `€${totalRevenue.toFixed(2)}`],
      ['Average €/kg', totalYield > 0 ? `€${(totalRevenue / totalYield).toFixed(2)}` : '€0.00'],
    ],
    theme: 'grid',
    headStyles: { fillColor: [74, 124, 46], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 10, right: 10 },
  });
  y = doc.lastAutoTable.finalY + 10;

  // Per-crop breakdown
  const cropMap = {};
  yearH.forEach(h => {
    if (!cropMap[h.cropId]) cropMap[h.cropId] = { yield: 0, revenue: 0, count: 0 };
    const w = parseFloat(h.weight) || 0;
    cropMap[h.cropId].yield += w;
    cropMap[h.cropId].revenue += w * (parseFloat(h.pricePerKg) || 0);
    cropMap[h.cropId].count++;
  });

  const cropRows = Object.entries(cropMap)
    .sort((a, b) => b[1].revenue - a[1].revenue)
    .map(([id, d]) => {
      const crop = crops.find(c => c.id === id);
      return [crop?.name || 'Unknown', d.count, `${d.yield.toFixed(1)} kg`, `€${d.revenue.toFixed(2)}`, d.yield > 0 ? `€${(d.revenue / d.yield).toFixed(2)}` : '—'];
    });

  if (cropRows.length > 0) {
    doc.setFontSize(12);
    doc.text('Per-Crop Breakdown', 10, y);
    y += 4;
    doc.autoTable({
      startY: y,
      head: [['Crop', 'Harvests', 'Yield', 'Revenue', '€/kg']],
      body: cropRows,
      theme: 'striped',
      headStyles: { fillColor: [74, 124, 46], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 10, right: 10 },
    });
  }

  addFooter(doc);
  doc.save(`${farmName.replace(/\s+/g, '-')}-harvest-report-${year}.pdf`);
}

// --- Export 4: Nursery Schedule ---
export async function exportNurserySchedulePdf({ zones, crops, settings, user }) {
  const JsPDF = await loadJsPDF();
  const farmName = user?.profile?.farmName || 'My Farm';
  const year = settings?.currentYear || new Date().getFullYear();
  const doc = createDoc(JsPDF, `Nursery Schedule ${year}`, farmName);

  const entries = [];
  (zones || []).forEach(z => (z.beds || []).forEach(b => {
    (b.plantings || []).forEach(p => {
      if (p.year !== year) return;
      const crop = crops.find(c => c.id === p.cropId);
      if (!crop) return;
      const sw = parseInt(p.startWeek);
      if (isNaN(sw)) return;
      const propagation = crop.daysInCell > 0 ? 'Indoor' : 'Direct Sow';
      const area = (b.width || 0.75) * (b.length || 10) * (p.bedFraction || 1);
      const plantsPerM2 = crop.spacing && crop.rowSpacing ? (100 / crop.spacing) * (100 / crop.rowSpacing) : 10;
      const plants = Math.ceil(area * plantsPerM2);
      entries.push([crop.name, b.name, z.name, propagation, `Week ${sw}`, `${area.toFixed(1)} m²`, plants]);
    });
  }));

  let y = 26;
  doc.setFontSize(14);
  doc.text(`Nursery Schedule — ${year}`, 10, y);
  y += 8;

  if (entries.length > 0) {
    doc.autoTable({
      startY: y,
      head: [['Crop', 'Bed', 'Zone', 'Method', 'Start', 'Area', 'Plants']],
      body: entries,
      theme: 'striped',
      headStyles: { fillColor: [74, 124, 46], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 10, right: 10 },
    });
  } else {
    doc.setFontSize(10);
    doc.text('No plantings scheduled for this year.', 10, y + 10);
  }

  addFooter(doc);
  doc.save(`${farmName.replace(/\s+/g, '-')}-nursery-${year}.pdf`);
}

// --- Export 5: Analytics / P&L Report ---
export async function exportAnalyticsReportPdf({ harvests, expenses, laborLogs, crops, zones, settings, user }) {
  const JsPDF = await loadJsPDF();
  const farmName = user?.profile?.farmName || 'My Farm';
  const year = settings?.currentYear || new Date().getFullYear();
  const doc = createDoc(JsPDF, `Analytics Report ${year}`, farmName);

  const yearH = (harvests || []).filter(h => new Date(h.date).getFullYear() === year);
  const yearE = (expenses || []).filter(e => new Date(e.date).getFullYear() === year);
  const yearL = (laborLogs || []).filter(l => new Date(l.date).getFullYear() === year);

  const totalRevenue = yearH.reduce((s, h) => s + (parseFloat(h.weight) || 0) * (parseFloat(h.pricePerKg) || 0), 0);
  const totalExpCost = yearE.reduce((s, e) => s + (parseFloat(e.amount) || 0), 0);
  const totalLaborCost = yearL.reduce((s, l) => s + (parseFloat(l.hours) || 0) * (parseFloat(l.hourlyRate) || 0), 0);
  const totalExpenses = totalExpCost + totalLaborCost;
  const netProfit = totalRevenue - totalExpenses;
  const margin = totalRevenue > 0 ? ((netProfit / totalRevenue) * 100).toFixed(1) : '0.0';

  let y = 26;
  doc.setFontSize(14);
  doc.text(`Profit & Loss — ${year}`, 10, y);
  y += 10;

  doc.autoTable({
    startY: y,
    head: [['Item', 'Amount']],
    body: [
      ['Total Revenue', `€${totalRevenue.toFixed(2)}`],
      ['Total Expenses', `€${totalExpenses.toFixed(2)}`],
      ['  - Direct Expenses', `€${totalExpCost.toFixed(2)}`],
      ['  - Labor Costs', `€${totalLaborCost.toFixed(2)}`],
      ['Net Profit', `€${netProfit.toFixed(2)}`],
      ['Profit Margin', `${margin}%`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [74, 124, 46], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 10, right: 10 },
  });
  y = doc.lastAutoTable.finalY + 10;

  // Expense breakdown by category
  const catMap = {};
  yearE.forEach(e => { catMap[e.category] = (catMap[e.category] || 0) + (parseFloat(e.amount) || 0); });
  catMap.labor = (catMap.labor || 0) + totalLaborCost;
  const catRows = Object.entries(catMap).filter(([, v]) => v > 0).sort((a, b) => b[1] - a[1]).map(([cat, amount]) => {
    const labels = { seeds: 'Seeds', labor: 'Labor', inputs: 'Inputs', equipment: 'Equipment', water: 'Water', other: 'Other' };
    return [labels[cat] || cat, `€${amount.toFixed(2)}`, totalExpenses > 0 ? `${((amount / totalExpenses) * 100).toFixed(0)}%` : '0%'];
  });

  if (catRows.length > 0) {
    doc.setFontSize(12);
    doc.text('Expense Breakdown', 10, y);
    y += 4;
    doc.autoTable({
      startY: y,
      head: [['Category', 'Amount', '% of Total']],
      body: catRows,
      theme: 'striped',
      headStyles: { fillColor: [74, 124, 46], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 10, right: 10 },
    });
  }

  addFooter(doc);
  doc.save(`${farmName.replace(/\s+/g, '-')}-analytics-${year}.pdf`);
}
