const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

export function printFarmCalendar({ zones, crops, settings, user }) {
  const year = settings?.currentYear || new Date().getFullYear();
  const lastFrost = settings?.lastFrostWeek || 12;
  const firstFrost = settings?.firstFrostWeek || 44;
  const farmName = user?.profile?.farmName || 'My Farm';

  // Gather all plantings for this year
  const monthData = MONTHS.map(() => ({ sow: [], transplant: [], harvest: [] }));

  (zones || []).forEach(z => (z.beds || []).forEach(b => {
    (b.plantings || []).forEach(p => {
      if (p.year !== year) return;
      const crop = crops.find(c => c.id === p.cropId);
      if (!crop) return;
      const startWeek = parseInt(p.startWeek);
      if (isNaN(startWeek)) return;

      // Sow month
      const sowMonth = weekToMonth(startWeek);
      if (sowMonth >= 0 && sowMonth < 12) {
        if (!monthData[sowMonth].sow.find(x => x.id === crop.id)) {
          monthData[sowMonth].sow.push({ id: crop.id, name: crop.name, icon: crop.icon });
        }
      }

      // Transplant month
      const daysInCell = crop.daysInCell || 0;
      if (daysInCell > 0) {
        const transplantWeek = startWeek + Math.ceil(daysInCell / 7);
        const tMonth = weekToMonth(transplantWeek);
        if (tMonth >= 0 && tMonth < 12) {
          if (!monthData[tMonth].transplant.find(x => x.id === crop.id)) {
            monthData[tMonth].transplant.push({ id: crop.id, name: crop.name, icon: crop.icon });
          }
        }
      }

      // Harvest month
      const harvestWeek = startWeek + Math.ceil((crop.daysToMaturity || 60) / 7);
      const hMonth = weekToMonth(harvestWeek);
      if (hMonth >= 0 && hMonth < 12) {
        if (!monthData[hMonth].harvest.find(x => x.id === crop.id)) {
          monthData[hMonth].harvest.push({ id: crop.id, name: crop.name, icon: crop.icon });
        }
      }
    });
  }));

  const renderList = (items, color) =>
    items.map(i => `<span style="display:inline-block;padding:1px 6px;margin:1px;border-radius:4px;font-size:10px;background:${color}15;color:${color};border:1px solid ${color}30">${i.icon} ${i.name}</span>`).join('');

  const monthCells = MONTHS.map((name, i) => {
    const d = monthData[i];
    const isEmpty = d.sow.length === 0 && d.transplant.length === 0 && d.harvest.length === 0;
    return `
      <td style="vertical-align:top;padding:8px;border:1px solid #ddd;width:33.33%;height:140px;background:#fff">
        <div style="font-weight:700;font-size:13px;margin-bottom:6px;color:#2c1810;border-bottom:2px solid #4a7c2e;padding-bottom:4px">${name}</div>
        ${isEmpty ? '<div style="color:#999;font-size:10px;font-style:italic">No plantings</div>' : ''}
        ${d.sow.length ? `<div style="margin-bottom:4px"><div style="font-size:9px;font-weight:700;color:#16a34a;text-transform:uppercase;letter-spacing:0.5px">Sow</div>${renderList(d.sow, '#16a34a')}</div>` : ''}
        ${d.transplant.length ? `<div style="margin-bottom:4px"><div style="font-size:9px;font-weight:700;color:#2563eb;text-transform:uppercase;letter-spacing:0.5px">Transplant</div>${renderList(d.transplant, '#2563eb')}</div>` : ''}
        ${d.harvest.length ? `<div><div style="font-size:9px;font-weight:700;color:#d97706;text-transform:uppercase;letter-spacing:0.5px">Harvest</div>${renderList(d.harvest, '#d97706')}</div>` : ''}
      </td>
    `;
  });

  // Build 3-column grid (4 rows × 3 months)
  let tableRows = '';
  for (let row = 0; row < 4; row++) {
    tableRows += `<tr>${monthCells[row * 3]}${monthCells[row * 3 + 1]}${monthCells[row * 3 + 2]}</tr>`;
  }

  const frostWeekToDate = (week) => {
    const jan1 = new Date(year, 0, 1);
    const d = new Date(jan1.getTime() + (week - 1) * 7 * 86400000);
    return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
  };

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>${farmName} - Farm Calendar ${year}</title>
  <style>
    @media print {
      body { margin: 0; }
      .no-print { display: none !important; }
    }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #2c1810; padding: 20px; }
    table { border-collapse: collapse; width: 100%; }
  </style>
</head>
<body>
  <div style="text-align:center;margin-bottom:20px">
    <h1 style="margin:0;font-size:24px;color:#2c1810">🌱 ${farmName} — Farm Calendar ${year}</h1>
    <div style="font-size:12px;color:#8b7355;margin-top:6px">
      Last Frost: ~${frostWeekToDate(lastFrost)} (Week ${lastFrost}) &nbsp;|&nbsp; First Frost: ~${frostWeekToDate(firstFrost)} (Week ${firstFrost})
    </div>
  </div>
  <table>${tableRows}</table>
  <div style="margin-top:12px;font-size:10px;color:#999;display:flex;justify-content:space-between">
    <span>Generated by BioGrow — ${new Date().toLocaleDateString('en-GB')}</span>
    <span class="no-print" style="cursor:pointer;color:#4a7c2e;font-weight:600" onclick="window.print()">🖨️ Print this page</span>
  </div>
</body>
</html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
}

function weekToMonth(week) {
  if (week < 1) return 0;
  if (week > 52) return 11;
  // Approximate: week 1 = Jan, week 5 = Feb, etc.
  const d = new Date(new Date().getFullYear(), 0, 1);
  d.setDate(d.getDate() + (week - 1) * 7);
  return d.getMonth();
}
